### PR TITLE
Switch from the NoFork terminology to the TerraformPluginSDK terminology and bump dependencies

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

In this PR:
- Switch from the NoFork terminology to the TerraformPluginSDK terminology
- Bump crossplane-runtime version to `v1.15.1`
- Bump upjet version to `v1.1.1`

I have:

- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

Tested with uptest below

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/applications/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/groups/member.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/serviceprincipals/principal.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/federatedidentitycredential.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/conditionalaccess/location.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/serviceprincipals/certificate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/synchronization/secret.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf LGTM! Please see @ulucinar's [comment](https://github.com/upbound/provider-azuread/pull/102#discussion_r1499328110) about fixing the dependencies.

**Comment by turkenf** [comment]
/test-examples="examples/applications/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/serviceprincipals/principal.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/synchronization/secret.yaml"

**Pull request merged**
